grafana:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    hosts:
      - ""
    paths:
      - /grafana(/|$)(.*)
    pathType: Prefix

prometheus:
  penabled: true

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true