grafana:
  env:
    GF_PATHS_CONFIG: /etc/grafana/grafana.ini
  enabled: true
  # Настройки Grafana.ini через отдельную секцию
  grafana.ini:
    server:
      #root_url: "http://158.160.173.65/grafana/"
      #root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true  # Включаем обработку подпутей
      #enforce_domain: false  # Отключает проверку домена
  # Настройки сервиса
  service:
    type: ClusterIP
    port: 80  # Порт сервиса (ClusterIP/NodePort)
    targetPort: 3000  # Порт контейнера Grafana
  # Настройки Ingress
  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   annotations:
  #     nginx.ingress.kubernetes.io/rewrite-target: /
  #   hosts:
  #     - ""
  #   paths:
  #     - path: /grafana
  #       pathType: Prefix

prometheus:
  penabled: true

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true