grafana:
  enabled: true
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/grafana$ $scheme://$http_host/grafana/ permanent;
    hosts:
      - ""
    paths:
      - /grafana(/|$)(.*)
    pathType: Prefix

prometheus:
  penabled: true

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true