grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
    port: 3000
  # ingress:
  #   enabled: true
  #   annotations: {}
  #   labels: {}
  #   ingressClassName: nginx
  #   hosts:
  #     - ""
  #   paths:
  #     - /grafana/*
    pathType: Prefix

prometheus:
  penabled: true

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true