grafana:
  enabled: true
  # Конфигурация сервиса
  service:
    type: NodePort
    port: 80 # Порт сервиса внутри кластера
    targetPort: 3000 # Порт контейнера Grafana
    nodePort: 24807   # Явно заданный порт на нодах Kubernetes
  # Конфигурация Ingress
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    paths:
      - path: /
        pathType: Prefix

prometheus:
  penabled: true

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true