name: IaC & K8s Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

env:
  K8S_CLUSTER_NAME: yc-k8s-cluster

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_KEY }}
      TF_VAR_YC_S3_BUCKET: ${{ secrets.YC_S3_BUCKET }}
      TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_yc_sa_key: ${{ secrets.YC_SA_KEY }}
      TF_VAR_yc_sa_id: ${{ secrets.YC_SA_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.YC_SSH_PUBLIC_KEY }}
      TF_VAR_ssh_username: ${{ secrets.YC_SSH_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=$TF_VAR_YC_S3_BUCKET"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Generate Inventory
        run: |
          mkdir -p tmp/inventory
          terraform output -raw kubespray_inventory > tmp/inventory/hosts.yaml

          # Debug вывод
          echo "=== DEBUG: INVENTORY CONTENTS ==="
          cat tmp/inventory/hosts.yaml
          echo "==============================="