name: IaC & K8s Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_KEY }}
  TF_VAR_YC_S3_BUCKET: ${{ secrets.YC_S3_BUCKET }}
  TF_VAR_YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  TF_VAR_YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}

  
jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Шаги из предыдущего примера для Terraform
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=$TF_VAR_YC_S3_BUCKET"

      - name: Terraform Apply
        run: terraform apply -auto-approve