name: IaC & K8s Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

env:
  K8S_CLUSTER_NAME: yc-k8s-cluster

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_KEY }}
      TF_VAR_YC_S3_BUCKET: ${{ secrets.YC_S3_BUCKET }}
      TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_yc_sa_key: ${{ secrets.YC_SA_KEY }}
      TF_VAR_yc_sa_id: ${{ secrets.YC_SA_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.YC_SSH_PUBLIC_KEY }}
      TF_VAR_ssh_username: ${{ secrets.YC_SSH_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=$TF_VAR_YC_S3_BUCKET"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Generate Inventory
        run: |
          mkdir -p tmp/inventory
          terraform output -raw kubespray_inventory > tmp/inventory/hosts.yaml

          # Debug вывод
          echo "=== DEBUG: INVENTORY CONTENTS ==="
          cat tmp/inventory/hosts.yaml
          echo "==============================="

  kubespray:
    name: "Deploy Kubernetes"
    runs-on: ubuntu-latest
    needs: terraform
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: kubespray

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          pip install --upgrade pip
          pip install -r kubespray/requirements.txt

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.YC_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Preparing Kubespray
        working-directory: ./kubespray
        run: |
          mkdir -p inventory/$K8S_CLUSTER_NAME
          cp -rfp inventory/sample inventory/$K8S_CLUSTER_NAME
          mv /tmp/hosts.yml inventory/$K8S_CLUSTER_NAME/

      - name: Run Kubespray
        working-directory: ./kubespray
        run: |
          ansible-playbook -i ../inventory/$K8S_CLUSTER_NAME/hosts.yaml \
            --private-key ~/.ssh/id_rsa \
            -u ${{ secrets.YC_SSH_USERNAME }} \
            -b --become-user=root \
            cluster.yml